### ISSUE TITLE
Frame drops when playing video

### ISSUE THREAD

**Issue by Kevga** [rie-kumar/MusicVideoPlayer#27]
The game starts to stutter when a video plays during gameplay. It gets worse if I select one of the "Background" positions where the render target is larger. SteamVR shows low GPU utilization (about 3 ms required per frame), so the bottleneck is probably somewhere else. MSI Afterburner confirms low GPU utilization but shows constant up-and-down in the frame time graph. No such issues when the video player is not on screen. Is there something wrong on my end or can the plugin be optimized somehow?

My specs:
Intel i7 8700K
Nvidia GTX 1080
32 GB 3200 MHz DDR4

**Comment by Kevga** [comment]
I did some more testing and noticed frame drops whenever the video screen is visible, even when no video is playing, like in the main menu. The frame time spikes seem to happen regularly about every 1.5 seconds.

**Comment by Mace404** [comment]
Probably because its filling the logs like 750 times a second with:
`[CRITICAL @ 21:18:26 | UnityEngine] NullReferenceException
[CRITICAL @ 21:18:26 | UnityEngine] UnityEngine.Transform.get_position () (at <6a27f5ccf1f84e47b130b28f8d65abee>:0)
[CRITICAL @ 21:18:26 | UnityEngine] MusicVideoPlayer.Utils.SoftParent.Update () (at <50b6aabf87f54bab93d316559e07d30f>:0)`

**Comment by b-rad15** [comment]
don't think that's causing the issue but just fixed that, will push the build soon™

**Comment by Kevga** [comment]
Have not noticed the issue anymore for a while. I'll close this for now.
