### ISSUE TITLE
Switch to Youtube-dlc?

### ISSUE THREAD

**Issue by Mace404** [rie-kumar/MusicVideoPlayer#41]
With the takedown of yt-dl and the recent change on the jsplayer by Google the current yt-dl with this addon is not working anymore.

Is it an idea to switch to Youtuble-dlc? https://github.com/blackjack4494/yt-dlc
Also having an option to specify your own cookie will prevent banning of IP

**Comment by b-rad15** [comment]
I was going to do this but now that youtube-dl is back working I am just going to continue with that. Thank you for letting me know about it though!

Also I've never seen the issue of ip banning. I could allow people to specify their own cookies but I think that would be more than the average person could figure out. If you see that as an issue though feel free to put it in as an issue. I could implement it but wouldn't know how to test it because I've never run into it so I'm not sure if it would be reproduceable.
